### ISSUE TITLE
compatibility with other jetbrains IDEs

### ISSUE THREAD

**Issue by azrdev** [tscheinecker/intellij-idea-coco-r-plugin#1]
[The plugin repo page](https://plugins.jetbrains.com/plugin/10406-coco-r)[1] shows compatibility with IDEA and Android Studio only, what prevents the plugin from being compatible with e.g. Rider (C#) or CLion (C/C++)? Integration with their "main language" as coco template language wouldn't needed for that in the first place.
[My previous attempt for a plugin](https://github.com/azrdev/coco-idea-plugin/) lists quite a lot of them other IDEs, although I'm not quite as feature-rich as you, didn't even get to finish the template language integration.

[1] would you mind adding that link prominently to the README?

**Comment by tscheinecker** [comment]
i just introduced a new section in the readme giving some information about why the plugin currently cannot be used with any non Java supporting IDEs

i also included a reference to your plugin there

i'll keep this issue open until i get around to get rid of this dependency (or somebody contributes this change)
